# Generated by Django 3.2 on 2022-10-30 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_community_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='admin_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='breed',
            name='breed_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dog_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='is_adopted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='is_adoption_ready',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='is_disable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_location',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='eventsubscriptions',
            name='subscription_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reports',
            name='last_known_location',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
