# Generated by Django 3.2 on 2022-10-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_community_app', '0002_auto_20221030_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_location',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='reports',
            name='last_known_location',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.CharField(max_length=5000),
        ),
    ]
