# Generated by Django 3.2 on 2022-11-04 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_community_app', '0002_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
            ],
        ),
    ]
