# Generated by Django 4.1.2 on 2022-12-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_community_app', '0002_eventsubscription_delete_eventsubscriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breed_image_path',
            field=models.ImageField(default='images/default_event.jpg', upload_to='images/breeds'),
        ),
        migrations.AlterField(
            model_name='dogs',
            name='dog_image',
            field=models.ImageField(default='images/default_event.jpg', upload_to='images/dogs'),
        ),
    ]
