# Generated by Django 3.2 on 2022-10-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_community_app', '0003_auto_20221030_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.CharField(max_length=4000),
        ),
    ]
