# Generated by Django 3.2 on 2022-11-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dog_community_app', '0003_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
