# Generated by Django 4.1.2 on 2022-11-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_community_app', '0003_team_alter_admin_admin_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member_image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
