# Generated by Django 3.2 on 2022-10-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_community_app', '0004_alter_events_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.TextField(max_length=5000),
        ),
    ]
