# Generated by Django 4.1.2 on 2022-11-06 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_community_app', '0004_team_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogs',
            name='disabilty',
            field=models.CharField(blank=True, max_length=5000),
        ),
    ]
