# Generated by Django 4.1.2 on 2022-11-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_community_app', '0005_alter_dogs_disabilty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
