# Generated by Django 3.2 on 2022-10-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_community_app', '0006_remove_events_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_description',
            field=models.CharField(default=None, max_length=5000),
            preserve_default=False,
        ),
    ]
