# Generated by Django 4.1.2 on 2022-11-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_community_app', '0008_remove_breed_breed_article_breed_bred_for_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='breed_article',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
