# Generated by Django 4.1.2 on 2022-12-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_community_app', '0011_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogs',
            name='dog_image_upload',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
